function [fitresult, gof] = exp_fit(fit1, fit2)
%CREATEFIT(FIT1,FIT2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fit1
%      Y Output: fit2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-May-2016 17:39:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fit1, fit2 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.StartPoint = [0.216003061043337 0.00765754608300775
%-0.255952690098894 -0.261111886074989]; when full power, unscaled
opts.StartPoint = [0.216003061043338 0.229726382490225 -0.255952690098898 -7.83335658224969]; % when scaled by 30
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



